version: "3"
services:
  mongo_mbapi:
    image: mongo
    volumes:
      - ./var/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kikirpa
      MONGO_INITDB_ROOT_PASSWORD: hescida
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_mbapi
      ME_CONFIG_MONGODB_ADMINUSERNAME: kikirpa
      ME_CONFIG_MONGODB_ADMINPASSWORD: hescida
