# generated by datamodel-codegen:
#   filename:  dendro_dating_measurement.json
#   timestamp: 2021-11-03T21:37:55+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field
from .document import Document


class General(BaseModel):
    dossier_code: Optional[str] = Field(None, title='Dossier code')
    object_number: Optional[float] = Field(None, title='Object code')


class Sample(BaseModel):
    collection: str = Field(..., title='Collection')
    sample_code: str = Field(..., title='Sample Code')
    characteristics: Optional[str] = Field(None, title='Characteristics')
    material: Optional[str] = Field(None, title='Material')


class Taxon(str, Enum):
    Abies_alba = 'Abies alba Mill.'
    Acer_campestre = 'Acer campestre L.'
    Acer_platanoides = 'Acer platanoides L.'
    Acer_pseudoplatanus = 'Acer pseudoplatanus L.'
    Aesculus_hippocastanum = 'Aesculus hippocastanum L.'
    Alnus_glutinosa = 'Alnus glutinosa Gaertn.'
    Alnus_incana = 'Alnus incana DC.'
    Alnus_viridis = 'Alnus viridis DC.'
    Amelanchier_ovalis = 'Amelanchier ovalis Med.'
    Berberis_vulgaris = 'Berberis vulgaris L.'
    Betula_alba = 'Betula alba (B. pendula / B. pubescens)'
    Betula_humilis = 'Betula humilis S'
    Betula_nana = 'Betula nana L.'
    Betula_pendula = 'Betula pendula Roth'
    Betula_pubescens = 'Betula pubescens Erh.'
    Buxus_sempervirens = 'Buxus sempervirens L.'
    Carpinus_betulus = 'Carpinus betulus L.'
    Castanea_sativa = 'Castanea sativa Gaertn.'
    Clematis_vitalba = 'Clematis vitalba L.'
    Cornus_mas = 'Cornus mas L.'
    Cornus_sanguinea = 'Cornus sanguinea L.'
    Corylus_avellana = 'Corylus avellana L.'
    Cotoneaster_integerrima = 'Cotoneaster integerrima Med.'
    Cotoneaster_tomentosa = 'Cotoneaster tomentosa Lindley'
    Crataegus_monogyna = 'Crataegus monogyna'
    Crataegus_oxyacantha = 'Crataegus oxyacantha'
    Cydonia_oblonga = 'Cydonia oblonga L.'
    Daphne_alpina = 'Daphne alpina L.'
    Daphne_cneorum = 'Daphne cneorum L.'
    Daphne_laureola = 'Daphne laureola L.'
    Daphne_mezereum = 'Daphne mezereum L.'
    Daphne_striata = 'Daphne striata Tratt.'
    Euonymus_europaeus = 'Euonymus europaeus L.'
    Euonymus_latifolius = 'Euonymus latifolius (L.) Mill.'
    Fagus_sylvatica = 'Fagus sylvatica L.'
    Frangula_alnus = 'Frangula alnus Mill.'
    Fraxinus_excelsior = 'Fraxinus excelsior L.'
    Hedera_helix = 'Hedera helix L.'
    Hippophae_rhamnoides = 'Hippophae rhamnoides L.'
    Ilex_aquifolium = 'Ilex aquifolium L.'
    Juglans_regia = 'Juglans regia L.'
    Juniperus_communis = 'Juniperus communis L.'
    Juniperus_nana = 'Juniperus nana Syme'
    Juniperus_sabina = 'Juniperus sabina L.'
    Laburnum_alpinum = 'Laburnum alpinum (Mill.) Prest.'
    Laburnum_anagyroides = 'Laburnum anagyroides Med.'
    Larix_decidua = 'Larix decidua Mill.'
    Ligustrum_vulgare = 'Ligustrum vulgare L.'
    Lonicera_alpigena = 'Lonicera alpigena L.'
    Lonicera_caprifolium = 'Lonicera caprifolium L.'
    Lonicera_coerulea = 'Lonicera coerulea L.'
    Lonicera_nigra = 'Lonicera nigra L.'
    Lonicera_periclymenum = 'Lonicera periclymenum L.'
    Lonicera_xylosteum = 'Lonicera xylosteum L.'
    Mespilus_germanica = 'Mespilus germanica L.'
    Ostrya_carpinifolia = 'Ostrya carpinifolia Scop.'
    Picea_abies = 'Picea abies Karsten'
    Pinus_Cembra = 'Pinus cembra L.'
    Pinus_Strobus = 'Pinus strobus L.'
    Pinus_mugo = 'Pinus mugo Turra'
    Pinus_nigra = 'Pinus nigra Arnold'
    Pinus_silvestris = 'Pinus silvestris L.'
    Pirus_communis = 'Pirus communis L.'
    Pirus_malus = 'Pirus malus L.'
    Platanus_orientalis = 'Platanus orientalis L. / P. occidentalis L.'
    Populus_alba = 'Populus alba L.'
    Populus_italica = 'Populus italica L.'
    Populus_nigra = 'Populus nigra L.'
    Populus_tremula = 'Populus tremula L.'
    Prunus_armeniaca = 'Prunus armeniaca L.'
    Prunus_avium = 'Prunus avium L.'
    Prunus_cerasifera = 'Prunus cerasifera Ehrh.'
    Prunus_cerasus = 'Prunus cerasus L.'
    Prunus_domestica = 'Prunus domestica L.'
    Prunus_insititia = 'Prunus insititia Julsen'
    Prunus_mahaleb = 'Prunus mahaleb L.'
    Prunus_padus = 'Prunus padus L.'
    Prunus_persica = 'Prunus persica (L.) Batsch'
    Prunus_spinosa = 'Prunus spinosa L.'
    Pseudotsuga_menziesii = 'Pseudotsuga menziesii (Mirb.) Franco'
    Quercus_petraea = 'Quercus petraea Liebl.'
    Quercus_pubescens = 'Quercus pubescens Willd.'
    Quercus_robur = 'Quercus robur L.'
    Rhamnus_cathartica = 'Rhamnus cathartica L.'
    Ribes_alpinum = 'Ribes alpinum L.'
    Ribes_nigrum = 'Ribes nigrum L.'
    Ribes_petraeum = 'Ribes petraeum Wulf.'
    Ribes_rubrum = 'Ribes rubrum L.'
    Ribes_uva_crispa = 'Ribes uva-crispa L.'
    Robinia_pseudoacacia = 'Robinia pseudoacacia L.'
    Rosa_arvensisn = 'Rosa arvensis Hudson'
    Rosa_canina = 'Rosa canina L.'
    Rosa_glauca = 'Rosa glauca Pourret'
    Rosa_pendulina = 'Rosa pendulina L.'
    Rosa_villosa = 'Rosa villosa L.'
    Salix_alba = 'Salix alba L.'
    Salix_appendiculata = 'Salix appendiculata Vill.'
    Salix_arbuscula = 'Salix arbuscula'
    Salix_aurita = 'Salix aurita L.'
    Salix_breviserrata = 'Salix breviserrata Flod.'
    Salix_caprea = 'Salix caprea L.'
    Salix_cinerea = 'Salix cinerea L.'
    Salix_daphnoides = 'Salix daphnoides Vill.'
    Salix_glabra = 'Salix glabra Scop.'
    Salix_glaucosericea = 'Salix glaucosericea Flod.'
    Salix_hastata = 'Salix hastata L.'
    Salix_helvetica = 'Salix helvetica Vill.'
    Salix_herbacea = 'Salix herbacea L.'
    Salix_incana = 'Salix incana'
    Salix_myrsinifolia = 'Salix myrsinifolia Salisb.'
    Salix_purpurea = 'Salix purpurea L.'
    Salix_repens = 'Salix repens L.'
    Salix_reticulata = 'Salix reticulata L.'
    Salix_retusa = 'Salix retusa L.'
    Salix_viminalis = 'Salix viminalis L.'
    Salix_waldsteiniana = 'Salix waldsteiniana Willd.'
    Sambucus_nigra = 'Sambucus nigra L.'
    Sambucus_racemosa = 'Sambucus racemosa L.'
    Sorbus_aria = 'Sorbus aria L.'
    Sorbus_aucuparia = 'Sorbus aucuparia L.'
    Sorbus_chamaemespilus = 'Sorbus chamaemespilus Crantz'
    Sorbus_domestica = 'Sorbus domestica L.'
    Sorbus_torminalis = 'Sorbus torminalis L.'
    Taxus_baccata = 'Taxus baccata L.'
    Tilia_cordata = 'Tilia cordata Mill.'
    Tilia_platyphyllos = 'Tilia platyphyllos Scop.'
    Ulmus_campestris = 'Ulmus campestris L.'
    Ulmus_laevis = 'Ulmus laevis Pallas'
    Ulmus_scabra = 'Ulmus scabra Mill.'
    Viburnum_lantana = 'Viburnum lantana L.'
    Viburnum_opulus = 'Viburnum opulus L.'
    Viscum_album = 'Viscum album L.'
    Vitis_vinifera = 'Vitis vinifera L.'


class Software(str, Enum):
    Dendron_IV = 'Dendron IV'
    CooRecorder = 'CooRecorder'


class MeasurementParameters(BaseModel):
    measurement_technique: str = Field(..., title='Measurement technique')
    measurement_date: date = Field(..., title='Measurement date')
    measurement_index: str = Field(..., title='Measurement index')
    taxon: Optional[Taxon] = Field(None)
    unit: Optional[str] = Field(None, title='Unit')
    software: Optional[Software] = Field(None)
    format: Optional[str] = Field(None, description='Data format', title='Format')

    class Config:
        title = "Measurement Parameters"


class Results(BaseModel):
    youngest_ring: Optional[str] = Field(None, title='Youngest ring')
    last_ring: Optional[str] = Field(None, title='Last ring')
    number_of_rings: Optional[float] = Field(
        None, description='Number of rings', title='Number of rings'
    )


class Dendro(Document):
    general: Optional[General] = Field(None)
    samples: Optional[List[Sample]] = Field(None)
    measurement_parameters: MeasurementParameters = Field(None)
    results: Optional[Results] = Field(None)
